name: app
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.0
  flutter:
    sdk: flutter
  flutter_bcrypt: ^1.0.5
  flutter_multi_formatter: ^1.3.6
  flutter_secure_storage: ^4.1.0
  flutter_svg: ^0.19.0
  http: ^0.12.2
  intl: ^0.17.0
  lint: ^1.5.3
  mockito: ^4.1.1+1
  shimmer: ^1.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/

  fonts:
    - family: Lato
      fonts:
        - asset: assets/fonts/Lato-Regular.ttf
        - asset: assets/fonts/Lato-Light.ttf
          weight: 100
